### ISSUE TITLE
Request to add Swagger Dependencies to POM file

### ISSUE THREAD

**Issue by garyrusso** [shawnbmccarthy/mdbSpringBootRestExample#1]
Please add the following dependency entries to the POM file.

`

		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger-ui</artifactId>
		    <version>2.7.0</version>
		</dependency>
		
		<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.7.0</version>
		</dependency>

`

**Comment by shawnbmccarthy** [comment]
POM file updated with dependencies
